canvas/src/layer/layer_2d.rs
canvas/src/text_brush.rs
canvas/src/wgpu_render.rs
canvas/src/wgpu_render/img_helper.rs
unit_test/src/lib.rs

This pr let image unit test use relative path of code file to access resource instead of relative to crate root.

use relative file path in unit test

---

core/src/declare.rs
core/src/state/stateful.rs
macros/Cargo.toml
macros/src/widget_macro/name_used_info.rs
ribir/examples/todo_mvp.rs
widgets/src/lists.rs
widgets/src/tabs.rs
widgets/src/text_field.rs
widgets/src/themes/material/ripple.rs

We do not watch anything in the closure body before, but it's not correct if the user defines a closure and calls it in the next line. For example:
```
widget! {
states { outside_state }
Text {
text: {
let c = move || outside_state.get_text();
x()
}
}
}
```
This example does not watch `outside_state`, It's wrong.
This fix will also watch the closure body, but remove the watch only if the closure is a field value directly.
#227 was merged in a mistake

fix(macros): 🐛 closure should also watch the states modifies.

---

macros/src/widget_macro.rs
macros/src/widget_macro/visit_mut.rs
macros/tests/code_gen_test.rs

embed states variable can not be directly used if the outside variable has the same name

fix(macros): 🐛 embed states variable can not be directly used

---

text/src/lib.rs
text/src/shaper.rs
text/src/typography.rs
text/src/typography_store.rs

This pr only fixes the chars not placed in the center with a line height. And some bugs leave that the typography store does not consider, vertical line and rtl. 
- we should refactor the typography man with an abstract axis and implement a convertor that converts the axis from the abstract axis to the visual axis.

fix(text): 🐛 inline offset should depends on font size

---

core/src/events.rs
core/src/events/character.rs
core/src/events/dispatcher.rs
core/src/events/focus.rs
core/src/events/focus_mgr.rs
core/src/events/keyboard.rs
core/src/events/listener_impl_helper.rs
core/src/events/pointers.rs
core/src/events/wheel.rs
docs/builtin_widget/declare_builtin_fields.md
macros/src/builtin_fields_list.rs

Ribir Framework only support bubble event now, some scenarios require event capture mechanisms, so support is needed.
Ribir Framework support events:
| Event Name     | Bubble | Capture |
| -------------- | ------ | ------- |
| chars          | true   | no yet  |
| focus          | false  | false   |
| blur           | false  | false   |
| focus in       | true   | no yet  |
| focus out      | true   | no yet  |
| key down       | true   | no yet  |
| key up         | true   | no yet  |
| pointer down   | true   | no yet  |
| pointer up     | true   | no yet  |
| pointer move   | true   | no yet  |
| tap            | true   | no yet  |
| pointer cancel | false  | false   |
| pointer enter  | false  | false   |
| pointer leave  | false  | false   |
| wheel          | true   | false   |
So …

feat(core): 🎸 support capture

---

gpu/src/gpu_backend/atlas.rs
gpu/src/gpu_backend/textures_mgr.rs

When the atlas expand, we copy whole texture from the old texture, but the not allocated area may be allocated to new resource. And we not require the gpu backend implementation to keep the order of the copy and write operation on the texture. So the overlap area may be wrong. We fix this to avoid copy the area we not allocated.

fix(gpu): 🐛 grow the atlas may miss the overlap area

---

core/src/builtin_widgets/anchor.rs
themes/material/src/lib.rs
widgets/src/input/editarea.rs

because user can use `pipe!` to do same thing in a easy way.

refactor(core): 💡 cancel anchor support percent unit

---

CHANGELOG.md
core/src/context/app_ctx.rs
core/src/state/stateful.rs
tests/rdl_macro_test.rs
widgets/src/text_field.rs

With the export of `FatObj::on_disposed`, the `on_state_drop` method, which was not particularly useful for unsubscribing the state, is no longer needed.
With the export of `FatObj::on_disposed`, the `on_state_drop` method, which was not particularly useful for unsubscribing the state, is no longer needed.

refactor(core): 💡 remove unused APIS

---

CHANGELOG.md
core/src/animation/transition.rs
core/src/builtin_widgets.rs
core/src/builtin_widgets/align.rs
core/src/builtin_widgets/anchor.rs
core/src/builtin_widgets/box_decoration.rs
core/src/builtin_widgets/cursor.rs
core/src/builtin_widgets/delay_drop.rs
core/src/builtin_widgets/fitted_box.rs
core/src/builtin_widgets/focus_node.rs
core/src/builtin_widgets/global_anchor.rs
core/src/builtin_widgets/has_focus.rs
core/src/builtin_widgets/layout_box.rs
core/src/builtin_widgets/margin.rs
core/src/builtin_widgets/mix_builtin.rs
core/src/builtin_widgets/mouse_hover.rs
core/src/builtin_widgets/opacity.rs
core/src/builtin_widgets/padding.rs
core/src/builtin_widgets/pointer_pressed.rs
core/src/builtin_widgets/scrollable.rs
core/src/builtin_widgets/transform_widget.rs
core/src/builtin_widgets/visibility.rs
core/src/declare.rs
macros/src/child_template.rs
macros/src/declare_derive.rs
macros/src/declare_obj.rs
macros/src/lib.rs
macros/src/simple_declare_attr.rs
tests/declare_builder_test.rs
widgets/src/layout/flex.rs

Simplify the names of the declare-related APIs
- `Declare::declare_builder` to `Declare::declarer`, 
- `DeclareBuilder` to `ObjDeclarer`, 
- `DeclareBuilder::build_declare` to `ObjDeclarer::finish`

refactor(core): 💡 simpler names for declare APIs

---

CHANGELOG.md
Cargo.toml
algo/Cargo.toml
algo/src/resource.rs
core/src/builtin_widgets/image_widget.rs
core/src/builtin_widgets/theme.rs
core/src/builtin_widgets/theme/icon_theme.rs
core/src/widget.rs
examples/messages/src/messages.rs
examples/storybook/src/storybook.rs
gpu/src/gpu_backend.rs
gpu/src/gpu_backend/textures_mgr.rs
painter/src/painter.rs
painter/src/style.rs
text/src/font_db.rs
widgets/src/avatar.rs
widgets/src/lists.rs

Clarify the usage of resources across painters, widgets, and wgpu rendering.

Remove share resource

---

Cargo.toml
ribir/Cargo.toml

Updated several image test cases due to changes made on the CI machine.
remove raw-window-handle

chore(ribir): 🤖 remove dep `raw-window-handle`

---

.github/workflows/dispatch-other-repo.yml

Forked repo not call website to sync docs

build(ribir): 🤖 forked repo not call website to sync docs

---

CHANGELOG.md
ribir/src/backends/wgpu_backend.rs

Crashes may occur when creating a zero-sized window. This can also happen when creating a normal window, if the platform initially creates it with zero size and delays resizing.

fix(ribir): 🐛 crash when creating a zero-sized window

---

CHANGELOG.md
cli/src/run_wasm.rs
core/src/builtin_widgets.rs
core/src/declare.rs
core/src/query.rs
core/src/render_helper.rs
core/src/state.rs
core/src/widget_children/child_convert.rs
macros/src/declare_derive.rs
widgets/src/avatar.rs
widgets/src/buttons.rs
widgets/src/checkbox.rs
widgets/src/input.rs
widgets/src/label.rs
widgets/src/lists.rs
widgets/src/tabs.rs

refactor(core): 💡 remove `StateFrom` and add `DeclareInto`

---

CHANGELOG.md
core/src/animation/stagger.rs
core/src/animation/transition.rs
core/src/pipe.rs
core/src/state.rs
core/src/state/stateful.rs
core/src/widget_tree/layout_info.rs
docs/en/get_started/quick_start.md
docs/zh/get_started/quick_start.md
examples/todos/src/ui.rs
tests/rdl_macro_test.rs

refactor(core): 💡 Removed unnecessary `Writer`

---

CHANGELOG.md
Cargo.toml
core/src/animation/stagger.rs
macros/src/error.rs
macros/src/fn_widget_macro.rs
macros/src/lib.rs
macros/src/part_writer.rs
macros/src/symbol_process.rs
macros/src/variable_names.rs

Creating a writer from a mutable reference of a writer will automatically switch to the built-in widget if its reference is a built-in field or method.
Added the `part_writer!` macro to create a writer from a mutable reference of a writer will automatically switch to the built-in widget if its reference is a built-in field or method.
If you're working on a widget and need help …

feat(macros): 🎸 the `part_writer!` macro

---

CHANGELOG.md
core/src/animation/animate_state.rs
core/src/animation/transition.rs
core/src/builtin_widgets.rs
core/src/builtin_widgets/align.rs
core/src/builtin_widgets/anchor.rs
core/src/builtin_widgets/box_decoration.rs
core/src/builtin_widgets/constrained_box.rs
core/src/builtin_widgets/foreground.rs
core/src/builtin_widgets/ignore_pointer.rs
core/src/builtin_widgets/opacity.rs
core/src/builtin_widgets/padding.rs
core/src/builtin_widgets/painting_style.rs
core/src/builtin_widgets/smooth_layout.rs
core/src/builtin_widgets/transform_widget.rs
core/src/builtin_widgets/visibility.rs
core/src/state/stateful.rs
core/src/wrap_render.rs

Added the smooth widgets for transitioning the layout position and size.

feat(core): 🎸 added smooth widgets

---

CHANGELOG.md
Cargo.toml
core/src/context/app_ctx.rs
core/src/widget_children/compose_child_impl.rs
docs/en/understanding_ribir/without_dsl.md
docs/zh/understanding_ribir/without_dsl.md
examples/counter/src/lib.rs
examples/storybook/src/storybook.rs
macros/Cargo.toml
macros/src/declare_derive.rs
widgets/src/layout/flex.rs
widgets/src/link.rs

Add a quick function macro for every widget that derives `Declare`.

feat(macros): 🎸 implement same name macro for widget derive `Declare`

---

CHANGELOG.md
core/src/animation.rs
core/src/animation/keyframes.rs

`keyframes!` are utilized to manage the intermediate steps of animation states.

feat(core): 🎸 support keyframes for aniamtions

---

CHANGELOG.md
Cargo.toml

This pull request is to fix #685 by changing cargo.toml docs link, as suggested by @M-Adoo.

Fix broken documentation link in cargo

---

CHANGELOG.md
core/src/test_helper.rs
core/src/window.rs
ribir/src/app.rs

In some cases, Ribir wouldn't redraw the window even when a redraw event would be emitted.
For example, on my i3 setup if I go to another workspace and come back, the app wouldn't redraw and the window would stay blank.
Here is a video:
https://github.com/user-attachments/assets/ef7923bb-1c52-459f-b539-8b038f5634d2
If you're working on a widget and need help writing test cases, we …

Fix empty window after switching in some cases

---

CHANGELOG.md
core/src/builtin_widgets.rs
core/src/widget_children/compose_child_impl.rs
macros/src/child_template.rs

enables embedding declare template as child in widget with Vec of template

fix(core): 🐛 enables embedding declare template as child in widget with Vec of template

---

core/src/builtin_widgets/background.rs
core/src/builtin_widgets/border.rs
core/src/builtin_widgets/clip_boundary.rs
core/src/builtin_widgets/fitted_box.rs
core/src/builtin_widgets/image_widget.rs
core/src/builtin_widgets/padding.rs
core/src/builtin_widgets/svg.rs
core/src/builtin_widgets/transform_widget.rs
themes/material/src/state_layer.rs
widgets/src/divider.rs
widgets/src/icon.rs
widgets/src/input/text_glyphs.rs
widgets/src/progress.rs
widgets/src/transform_box.rs

Replace unwrap() with None checks when getting layout size.
Cases where layout size might be missing:
1. Called too early (before layout finishes)
2. Widgets under invisible parents (skipped in layout)
These cases could crash the app even when layout worked correctly.
If you're working on a widget and need help writing test cases, we have some macros that can assist you. Please …

fix(core): prevent panic in visual_box layout code

---

CHANGELOG.md
core/src/widget_children.rs
macros/src/child_template.rs
macros/src/simple_declare_attr.rs
macros/src/util.rs

Added `#[template(field)]` to support declaring field syntax for `Template`.

feat(core): 🎸 add non-child field support to `Template`

---

CHANGELOG.md
core/src/pipe.rs
core/src/query.rs

if pipe generate multi outer data of the first child is incorrectly wrapped to all

fix(core): 🐛 if pipe generate multi outer data of the first child is incorrectly wrapped to all

---

Cargo.toml
ribir/Cargo.toml
ribir/src/app.rs

fix bug: ribir run app with default theme of material light

fix(ribir): 🐛 ribir run app with default theme of material light
