canvas/src/wgpu_render.rs, canvas/src/wgpu_render/img_helper.rs, core/src/application.rs, core/src/widget.rs, core/src/widget/key.rs, core/src/widget/widget_tree.rs
after remove time of widget, we can use runtime type to check widget's key
=> Use runtime type to check widget's key

core/src/lib.rs, core/src/render.rs, core/src/widget.rs, core/src/widget/build_ctx.rs, core/src/widget/key.rs, core/src/widget/stateful.rs, core/src/widget/widget_tree.rs
Support event handler to change widget's state.
=> Build Context

canvas/examples/canvas_hello.rs, canvas/src/layer/layer_2d.rs, canvas/src/lib.rs
=> feat(canvas): canvas 2d ctx

core/Cargo.toml, core/src/lib.rs, core/src/widget.rs, core/src/widget/events.rs, core/src/widget/events/dispatch.rs, core/src/widget/events/focus.rs, core/src/widget/events/pointers.rs, core/src/widget/events/pointers/from_mouse.rs, core/src/widget/widget_tree.rs, core/src/widget/window.rs
=> feat: init focus manager

core/src/lib.rs, core/src/render/render_ctx.rs, core/src/widget.rs, core/src/widget/events/dispatcher/focus_mgr.rs, core/src/widget/margin.rs, core/src/widget/padding.rs
=> Padding & Margin

gpu/src/tessellator.rs, painter/src/color.rs
=> fix(painter): 🐛 linear color space convert

core/Cargo.toml, core/src/application.rs, core/src/builtin_widgets/theme/compose_styles.rs, core/src/lib.rs, core/src/test.rs, core/src/window.rs, ribir/examples/todo_mvp.rs, ribir/src/lib.rs
export application window init size
=> feat(ribir): 🎸 export define window size

docs/essentials/widget_language.md
I looked through the text from the start to line 292. I'm not a native speaker myself, but I hope the suggested changes are still an improvement. Because I edited this online (GitHub edit file functionality) I'd rater create a PR before I continue and risk losing work.
=> Attempt to improve the text

docs/project_practice/how_to_build_a_todo_application_with_ribir.md
I'm sure there is still room for improvement.
I found it sometimes just too verbose.
Please let me know if I butchered the original intent, so we can further improve it.
=> Improve the text

docs/getting_started/quick_start.md
I think it's better to suggest a git dependency for now and change the doc once Ribir is published to crates.io
=> Some text changes and ribir dependency changed to git

core/src/builtin_widgets/theme.rs, core/src/builtin_widgets/theme/typography_theme.rs, painter/src/painter.rs, painter/src/style.rs, ribir/examples/counter.rs, ribir/examples/greet.rs, ribir/examples/todo_mvp.rs, widgets/src/button.rs, widgets/src/checkbox.rs, widgets/src/input.rs, widgets/src/lists.rs, widgets/src/tabs.rs, widgets/src/text.rs, widgets/src/text_field.rs, widgets/src/themes/material.rs
reference: https://m3.material.io/styles/typography/type-scale-tokens
=> refactor(core): 💡 typography theme refactor

macros/src/widget_macro/code_gen.rs, macros/src/widget_macro/visit_mut.rs, tests/code_gen_test.rs
=> fix(macros): 🐛 do no track prop's lerp_fn closure

ribir/examples/storybook.rs, widgets/src/layout/column.rs, widgets/src/layout/flex.rs, widgets/src/layout/row.rs
`Flex` support main axis gap and cross_axis_gap, it's fixed size.
=> feat(widgets): 🎸 flex support main_axis_gap and cross_axis_gap

ribir/Cargo.toml, ribir/src/winit_shell_wnd.rs
=> fix(ribir): 🐛manually set sogou ime positon in windows platform

gpu/src/gpu_backend/textures_mgr.rs
we can't directly use address as the hash key, because the next resource may allocate at same address of last frame deallocated resource.
=> fix(gpu): 🐛 resource key address conflict

Cargo.toml, core/Cargo.toml, core/src/context.rs, core/src/context/app_ctx.rs, ribir/Cargo.toml
=> feat(core): 🎸 compatible with async futures that rely on tokio runtime

docs/zh/get_started/try_it.md
Fix the markdown format error.
=> docs(ribir): fix typo

CHANGELOG.md, README.md, docs/en/get_started/quick_start.md, docs/zh/get_started/quick_start.md, macros/src/rdl_macro.rs, tests/rdl_macro_test.rs
=> docs(ribir): ✏️ fix broken links and format the example code

CHANGELOG.md, core/src/builtin_widgets.rs, core/src/builtin_widgets/container.rs, core/src/builtin_widgets/focus_node.rs, core/src/builtin_widgets/focus_scope.rs, core/src/builtin_widgets/global_anchor.rs, core/src/context/build_ctx.rs, core/src/events/focus_mgr.rs, core/src/lib.rs, core/src/overlay.rs, core/src/pipe.rs, core/src/state/stateful.rs, core/src/test_helper.rs, core/src/widget_tree.rs, core/src/widget_tree/widget_id.rs, core/src/window.rs, docs/en/get_started/try_it.md, tests/rdl_macro_test.rs, widgets/src/layout.rs
=> feat(core): 🎸 overlay

CHANGELOG.md, README.md, docs/en/get_started/_category_.json, docs/en/get_started/try_it.md, docs/en/practice_todos_app/_category_.json, docs/en/understanding_ribir/_category_.json, docs/en/understanding_ribir/widget_in_depth.md, docs/en/understanding_ribir/without_dsl.md, docs/zh/get_started/try_it.md, docs/zh/understanding_ribir/widget_in_depth.md, docs/zh/understanding_ribir/without_dsl.md, widgets/src/buttons/filled_button.rs
=> docs(ribir): ✏️ update document "Use Ribir without DSL"

CHANGELOG.md, README.md, RELEASE.md, ROADMAP.md
=> docs(ribir): ✏️ add a roadmap

CHANGELOG.md
=> Merge 0.1.x

gpu/src/gpu_backend.rs, gpu/src/wgpu_impl.rs
=> Refactor img future

CHANGELOG.md, Cargo.toml, core/src/context/app_ctx.rs, core/src/overlay.rs, core/src/window.rs, examples/counter/src/main.rs, examples/messages/src/main.rs, examples/storybook/src/main.rs, examples/todos/src/main.rs, examples/wordle_game/src/main.rs, ribir/Cargo.toml, ribir/src/app.rs, ribir/src/winit_shell_wnd.rs
Simplified the startup process for a Ribir app, making it easier for users to configure the app and window.
=> feat(ribir): 🎸 introduced `AppRunGuard`

CHANGELOG.md, core/src/overlay.rs, core/src/test_helper.rs, core/src/window.rs, examples/counter/src/main.rs, examples/messages/src/main.rs, examples/storybook/src/main.rs, examples/todos/src/main.rs, examples/wordle_game/src/main.rs, ribir/Cargo.toml, ribir/src/app.rs, ribir/src/winit_shell_wnd.rs
- delay create window for `App::run`
- fix delay create window for `App::run`
=> Feat window attrs

.github/workflows/pr-num.yml
=> build(ribir): 🤖 `pr-num.yml` pull branch from fork repo

.github/workflows/ci.yml, CHANGELOG.md, core/Cargo.toml, core/src/overlay.rs, core/src/pipe.rs, core/src/state.rs, core/src/state/prior_op.rs, core/src/state/stateful.rs, core/src/test_helper.rs, core/src/widget_children.rs, core/src/widget_tree.rs, core/src/window.rs, dev-helper/Cargo.toml, dev-helper/src/image_test.rs, dev-helper/src/widget_test.rs
=> test(core): 💍 wasm test of core

CHANGELOG.md, cli/Cargo.toml, cli/src/run_wasm.rs
=> feat(cli): 🎸 wasm server watch file change

.github/workflows/patch-version.yml
This allows transitions from beta to rc, and rc to stable, without requiring new commits.
=> Allow version release without additional commits in the release branch

CHANGELOG.md
merge 0.2 release branch to master
=> Merge 0.2.x

Cargo.toml
=> build(ribir): 🤖 update triomphe to 0.1.12, rxRust to 1.0.0-beta.8

Cargo.toml, core/Cargo.toml, dev-helper/Cargo.toml, gpu/Cargo.toml, macros/Cargo.toml, macros/src/lib.rs, painter/Cargo.toml, ribir/Cargo.toml, text/Cargo.toml, themes/material/Cargo.toml, widgets/Cargo.toml
=> fix(macros): 🐛 release failed

CHANGELOG.md, core/src/state/splitted_state.rs
=> refactor(core): 💡 remove unused stamp checker

CHANGELOG.md, core/src/state.rs, core/src/state/map_state.rs, core/src/state/splitted_state.rs, core/src/state/state_cell.rs
The purpose of this Pull Request is accurately described in the title.
=> refactor(core): 💡 PartData<T> support T: ?Sized

CHANGELOG.md, macros/src/declare_obj.rs, tests/rdl_macro_test.rs
=> fix(macros): 🐛 variable parent with built-in fields need be mutable for its children

CHANGELOG.md, core/src/animation/animate.rs, core/src/builtin_widgets/smooth_layout.rs, core/src/test_helper.rs, core/src/ticker.rs, core/src/window.rs, painter/src/painter.rs
=> fix(core): 🐛 smooth layout should not trigger an animation during layout

Cargo.toml, cli/Cargo.toml, core/Cargo.toml, dev-helper/Cargo.toml, examples/counter/Cargo.toml, examples/counter/src/lib.rs, examples/messages/Cargo.toml, examples/messages/src/messages.rs, examples/storybook/Cargo.toml, examples/storybook/src/lib.rs, examples/todos/Cargo.toml, examples/todos/src/lib.rs, examples/wordle_game/Cargo.toml, examples/wordle_game/src/lib.rs, gpu/Cargo.toml, macros/Cargo.toml, painter/Cargo.toml, ribir/Cargo.toml, ribir/src/lib.rs, themes/material/Cargo.toml, themes/ribir_slim/Cargo.toml, widgets/Cargo.toml
=> build(ribir): 🤖 addressed issue with failed release

ribir/Cargo.toml
Fix repository URL, because current link will get 404 error.
=> Fix repository url

CHANGELOG.md, core/src/builtin_widgets/clip_boundary.rs, core/src/builtin_widgets/scrollable.rs, core/src/context/layout_ctx.rs, core/src/pipe.rs, core/src/widget_tree.rs, core/src/window.rs, examples/todos/src/ui.rs, painter/src/painter.rs
As described in the commit messages.
=> Rollup of clipping boundary and layout cache fixes

.github/workflows/ci.yml, .github/workflows/pr-num.yml, CHANGELOG.md, Cargo.toml, cli/Cargo.toml, core/Cargo.toml, dev-helper/Cargo.toml, gpu/Cargo.toml, macros/Cargo.toml, painter/Cargo.toml, ribir/Cargo.toml, themes/material/Cargo.toml, themes/ribir_slim/Cargo.toml, widgets/Cargo.toml
=> Fix Alpha Release Failure & PR Number Update Based on B-merge-ready Label

.github/workflows/pr-num.yml
=> build(ribir): 🤖 update-pr-number in merge queue

.github/workflows/pr-num.yml, core/src/builtin_widgets/color_filter.rs
=> refactor(core): 💡 make `ColorFilter` to be a `WrapRender`

.github/workflows/pr-num.yml, docs/en/practice_todos_app/develop_a_todos_app.md, docs/zh/practice_todos_app/develop_a_todos_app.md, examples/messages/src/messages.rs, examples/storybook/src/storybook.rs, examples/todos/src/ui.rs, widgets/src/icon.rs, widgets/src/tabs.rs
=> refactor(widgets): 💡 `Tab` syntax

macros/src/child_template.rs, widgets/src/common_widget.rs
=> refactor(widgets): 💡 Add support declare syntax for `Leading` and `Traling`

CHANGELOG.md, algo/src/cow_rc.rs, core/src/builtin_widgets/focus_scope.rs, core/src/events.rs, core/src/events/character.rs, core/src/events/device_id.rs, core/src/events/dispatcher.rs, core/src/events/focus_mgr.rs, core/src/events/pointers.rs, core/src/window.rs, ribir/src/app.rs, ribir/src/app/app_event_handler.rs, ribir/tests/timer_test.rs, tests/rdl_macro_test.rs, widgets/src/input.rs
=> fix(core): 🐛 remove erroneous input filtering of mouse event

CHANGELOG.md, core/src/builtin_widgets/focus_node.rs, core/src/builtin_widgets/focus_scope.rs, core/src/builtin_widgets/mix_builtin.rs, core/src/builtin_widgets/tooltips.rs, core/src/events.rs, core/src/events/dispatcher.rs, core/src/events/focus_mgr.rs, core/src/events/pointers.rs, core/src/window.rs, examples/counter/src/lib.rs, examples/todos/src/ui.rs, macros/src/variable_names.rs, themes/material/src/classes/input_cls.rs, themes/material/src/classes/scrollbar_cls.rs, themes/material/src/state_layer.rs, widgets/src/input/text_editable.rs, widgets/src/list.rs, widgets/src/menu.rs, widgets/src/text_field.rs
=> feat(core): 🎸 Add `FocusReason` to idicate the cause of focus change

CHANGELOG.md, core/src/events.rs, core/src/events/lifecycle.rs, core/src/lib.rs, core/src/reusable.rs, core/src/window.rs
=> feat(core): 🎸 add `Reusable` helper to enable widget recycling

CHANGELOG.md, core/src/pipe.rs
Fixed priority of the pipe not depend on its position(the position wasn't accurate tracked)
=> fix(core): 🐛 Priority of the pipe not depend on its position

CHANGELOG.md, Cargo.toml, core/src/builtin_widgets/reuse_id.rs, core/src/builtin_widgets/text.rs, core/src/builtin_widgets/widget_scope.rs, core/src/reusable.rs, core/src/test_helper.rs, gpu/src/wgpu_impl.rs, painter/src/image.rs, widgets/Cargo.toml, widgets/src/lib.rs, widgets/src/list.rs, widgets/src/router.rs
=> feat(widgets): 🎸 added `Router` widget

CHANGELOG.md, core/src/builtin_widgets/theme/typography_theme.rs, painter/src/painter.rs, painter/src/text.rs, painter/src/text/font_db.rs, themes/material/src/lib.rs
Established a standardized list of common fallback system fonts for the themes to utilize.
=> feat(core): 🎸 Added common fallback system fonts list function `fallback_font_families`

CHANGELOG.md, core/Cargo.toml, painter/Cargo.toml, painter/src/image.rs, ribir/Cargo.toml
=> feat(painter): 🎸 Support jepg image

macros/src/distinct_pipe_macro.rs
=> fix(core): 🐛 correctly `distinct_pipe!` first skip

Cargo.toml, painter/Cargo.toml, painter/src/color.rs
=> build(painter): 🤖 Remove the dependency on the getrandom-v2 crate

docs/en/get_started/quick_start.md, docs/en/practice_todos_app/develop_a_todos_app.md, docs/zh/get_started/quick_start.md, docs/zh/practice_todos_app/develop_a_todos_app.md
=> docs(core): ✏️ update example code in doc

docs/en/practice_todos_app/develop_a_todos_app.md, docs/zh/practice_todos_app/develop_a_todos_app.md
=> docs(examples): ✏️ update example code in doc
